apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    uid: cloudwatch
    isDefault: true
    jsonData:
      authType: default
      defaultRegion: eu-west-3
    editable: true

