apiVersion: 1

datasources:
  - name: Athena-DynamoDB
    type: grafana-athena-datasource
    access: proxy
    uid: athena-dynamodb
    isDefault: true
    jsonData:
      authType: default
      catalog: AwsDataCatalog
      database: ${ATHENA_DATABASE}
      defaultRegion: ${AWS_REGION}
      workgroup: ${ATHENA_WORKGROUP}
    editable: true

  - name: CloudWatch
    type: cloudwatch
    access: proxy
    uid: cloudwatch
    jsonData:
      authType: default
      defaultRegion: ${AWS_REGION}
    editable: true

